"""
ServiceNow ITSM Integration — Change Management & Incident Automation

Connects to: https://dev218436.service-now.com/
Supports: CHG (Change Requests), INC (Incidents), RITM (Requests)

Features:
  - Auto-create CHG tickets for low-confidence vulnerabilities
  - Create INC for detected active exploits
  - Link remediation results back to tickets
  - Approval workflow via ServiceNow
  - CMDB integration for server inventory
"""

import json
import logging
import base64
from datetime import datetime, timedelta
from typing import Dict, List, Optional
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


@dataclass
class ServiceNowConfig:
    """ServiceNow instance configuration."""
    instance_url: str = "https://dev218436.service-now.com"
    username: str = "admin"
    password: str = ""
    api_version: str = "v2"

    @property
    def base_api_url(self) -> str:
        return f"{self.instance_url}/api/now"

    @property
    def table_api_url(self) -> str:
        return f"{self.base_api_url}/table"

    @property
    def auth_header(self) -> str:
        credentials = base64.b64encode(
            f"{self.username}:{self.password}".encode()
        ).decode()
        return f"Basic {credentials}"


class ServiceNowClient:
    """
    ServiceNow REST API client for ITSM operations.
    Handles CHG, INC, and CMDB operations.
    """

    def __init__(self, config: ServiceNowConfig = None):
        self.config = config or ServiceNowConfig()
        self._session = None
        self._connected = False

    def _get_session(self):
        """Lazy-initialize requests session."""
        if self._session is None:
            try:
                import requests
                self._session = requests.Session()
                self._session.headers.update({
                    "Authorization": self.config.auth_header,
                    "Content-Type": "application/json",
                    "Accept": "application/json",
                })
                self._connected = True
            except ImportError:
                logger.warning("requests library not available — using simulation mode")
                self._connected = False
        return self._session

    @property
    def is_connected(self) -> bool:
        return self._connected

    def test_connection(self) -> Dict:
        """Test connectivity to ServiceNow instance."""
        session = self._get_session()
        if not session:
            return {"status": "SIMULATED", "message": "Running in simulation mode"}

        try:
            url = f"{self.config.table_api_url}/sys_properties?sysparm_limit=1"
            response = session.get(url, timeout=10)

            if response.status_code == 200:
                return {"status": "CONNECTED", "instance": self.config.instance_url}
            elif response.status_code == 401:
                return {"status": "AUTH_FAILED", "message": "Invalid credentials"}
            else:
                return {"status": "ERROR", "code": response.status_code}

        except Exception as e:
            return {"status": "ERROR", "message": str(e)}

    # ===================== CHANGE REQUESTS (CHG) =====================

    def create_change_request(
        self,
        vulnerability: Dict,
        server_context: Dict,
        decision=None,
        additional_fields: Dict = None,
    ) -> Dict:
        """
        Create a ServiceNow Change Request for vulnerability remediation.

        Maps vulnerability data to CHG fields:
          - short_description: CVE + title
          - description: Full analysis with NIST mapping
          - category: Security Patch
          - assignment_group: Windows Server Team
          - risk: Based on confidence score
          - impact: Based on severity
        """

        cve = vulnerability.get("cve_id", "Unknown CVE")
        title = vulnerability.get("title", "Vulnerability Remediation")
        severity = vulnerability.get("severity", "MEDIUM")
        description = vulnerability.get("description", "")
        kb = vulnerability.get("kb_number", "N/A")

        # Map severity to impact
        impact_map = {"CRITICAL": "1", "HIGH": "2", "MEDIUM": "2", "LOW": "3"}
        urgency_map = {"CRITICAL": "1", "HIGH": "2", "MEDIUM": "3", "LOW": "3"}
        risk_map = {"CRITICAL": "High", "HIGH": "High", "MEDIUM": "Moderate", "LOW": "Low"}

        confidence = decision.confidence_score if decision else 0.5
        nist = decision.nist_controls if decision else []

        # Build detailed description
        full_description = f"""AUTOMATED VULNERABILITY REMEDIATION REQUEST
Generated by: Agentic AI Windows Vulnerability Scanner
Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

=== VULNERABILITY DETAILS ===
CVE ID: {cve}
Title: {title}
Severity: {severity}
CVSS Score: {vulnerability.get('cvss_score', 'N/A')}
Description: {description}

=== TARGET SERVER ===
Instance ID: {server_context.get('instance_id', 'N/A')}
Account: {server_context.get('account_name', 'N/A')} ({server_context.get('account_id', 'N/A')})
OS Version: {server_context.get('os_version', 'N/A')}
Hostname: {server_context.get('hostname', 'N/A')}
Environment: {server_context.get('environment', 'N/A')}

=== COMPLIANCE MAPPING ===
NIST SP 800-53 Controls: {', '.join(nist) if nist else 'Pending mapping'}
KB Article: {kb}

=== AI AGENT ANALYSIS ===
Confidence Score: {confidence:.0%}
Routing Decision: Change Request (confidence below auto-remediation threshold)
{f'AI Reasoning: {decision.reasoning}' if decision and decision.reasoning else ''}

=== REMEDIATION PLAN ===
1. Create system restore point
2. Backup current registry state
3. Apply KB update: {kb}
4. Apply NIST-compliant registry fixes
5. Verify remediation success
6. Schedule reboot if required

=== ESTIMATED IMPACT ===
Duration: {decision.estimated_duration if decision else '15-30 minutes'}
Reboot Required: {'Yes' if (decision and decision.reboot_required) else 'TBD'}
Rollback Available: Yes (system restore point)
"""

        # Build CHG payload
        payload = {
            "short_description": f"[{severity}] {cve} - {title}",
            "description": full_description,
            "type": "Standard",
            "category": "Software",
            "subcategory": "Security Patch",
            "assignment_group": "Windows Server Team",
            "impact": impact_map.get(severity, "2"),
            "urgency": urgency_map.get(severity, "2"),
            "risk": risk_map.get(severity, "Moderate"),
            "priority": urgency_map.get(severity, "2"),
            "state": "-5",  # New
            "start_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "end_date": (datetime.now() + timedelta(days=7)).strftime("%Y-%m-%d %H:%M:%S"),
            "justification": f"Security vulnerability {cve} requires remediation. "
                             f"NIST controls: {', '.join(nist)}. "
                             f"AI confidence score: {confidence:.0%}.",
            "implementation_plan": f"1. Verify server availability\n"
                                   f"2. Create restore point\n"
                                   f"3. Install {kb}\n"
                                   f"4. Apply registry fixes\n"
                                   f"5. Verify and close",
            "backout_plan": "1. Restore from system restore point\n"
                           "2. Rollback registry changes from backup\n"
                           "3. Verify system stability",
            "test_plan": "1. Verify KB installation via Get-HotFix\n"
                        "2. Validate registry values\n"
                        "3. Run security baseline scan\n"
                        "4. Confirm no service disruption",
        }

        if additional_fields:
            payload.update(additional_fields)

        # API call
        return self._create_record("change_request", payload)

    # ===================== APPROVAL MANAGEMENT =====================

    def add_approver_to_change(self, chg_sys_id: str, approver_sys_id: str) -> Dict:
        """Add an approver to a change request."""
        return self._create_record("sysapproval_approver", {
            "sysapproval": chg_sys_id,
            "approver": approver_sys_id,
            "state": "requested",
            "source_table": "change_request",
        })

    def get_approval_status(self, chg_sys_id: str) -> List[Dict]:
        """Get approval status for a change request."""
        session = self._get_session()
        if not session:
            return [{"approver": "Security Approver", "state": "requested", "_simulated": True}]

        try:
            url = (
                f"{self.config.table_api_url}/sysapproval_approver"
                f"?sysparm_query=sysapproval={chg_sys_id}"
                f"&sysparm_fields=approver,state,sys_updated_on,comments"
            )
            response = session.get(url, timeout=10)
            if response.status_code == 200:
                return response.json().get("result", [])
            return []
        except Exception:
            return []

    def approve_change(self, approval_sys_id: str, comments: str = "Approved by VulnShield AI") -> Dict:
        """Approve a change request approval record."""
        return self.update_ticket("sysapproval_approver", approval_sys_id, {
            "state": "approved",
            "comments": comments,
        })

    def reject_change(self, approval_sys_id: str, comments: str = "Rejected") -> Dict:
        """Reject a change request approval record."""
        return self.update_ticket("sysapproval_approver", approval_sys_id, {
            "state": "rejected",
            "comments": comments,
        })

    def get_change_with_approvals(self, chg_number: str) -> Dict:
        """Get a change request with its approval status."""
        chg = self.get_ticket("change_request", chg_number)
        if chg and chg.get("sys_id"):
            approvals = self.get_approval_status(chg["sys_id"])
            chg["_approvals"] = approvals
        return chg

    # ===================== INCIDENTS (INC) =====================

    def create_incident(
        self,
        vulnerability: Dict,
        server_context: Dict,
        description: str = "",
    ) -> Dict:
        """Create a ServiceNow Incident for active exploit detection."""

        cve = vulnerability.get("cve_id", "Unknown")
        severity = vulnerability.get("severity", "HIGH")

        impact_map = {"CRITICAL": "1", "HIGH": "1", "MEDIUM": "2", "LOW": "3"}
        urgency_map = {"CRITICAL": "1", "HIGH": "1", "MEDIUM": "2", "LOW": "3"}

        payload = {
            "short_description": f"[SECURITY] Active exploit detected: {cve}",
            "description": description or f"Active exploitation of {cve} detected on "
                          f"{server_context.get('hostname', 'Unknown')} "
                          f"({server_context.get('instance_id', 'N/A')})",
            "category": "Security",
            "subcategory": "Vulnerability",
            "impact": impact_map.get(severity, "2"),
            "urgency": urgency_map.get(severity, "2"),
            "assignment_group": "Security Operations",
            "caller_id": "admin",
        }

        return self._create_record("incident", payload)

    # ===================== CMDB INTEGRATION =====================

    def sync_server_to_cmdb(self, server) -> Dict:
        """Sync a Windows server to ServiceNow CMDB."""
        payload = {
            "name": server.hostname,
            "ip_address": server.private_ip,
            "os": server.os_version,
            "os_version": server.os_build,
            "serial_number": server.instance_id,
            "category": "Server",
            "subcategory": "Windows",
            "environment": server.tags.get("Environment", "Production"),
            "operational_status": "1" if server.status == "Online" else "2",
            "comments": f"AWS Account: {server.account_id} | Region: {server.region}",
        }

        return self._create_or_update_record(
            "cmdb_ci_server", payload, query=f"serial_number={server.instance_id}"
        )

    # ===================== TICKET MANAGEMENT =====================

    def update_ticket(self, table: str, sys_id: str, updates: Dict) -> Dict:
        """Update an existing ticket."""
        session = self._get_session()
        if not session:
            return self._simulate_response(table, updates, sys_id=sys_id)

        try:
            url = f"{self.config.table_api_url}/{table}/{sys_id}"
            response = session.patch(url, json=updates, timeout=15)

            if response.status_code == 200:
                result = response.json().get("result", {})
                logger.info(f"Updated {table}/{sys_id}")
                return result
            else:
                logger.error(f"Update failed: {response.status_code} - {response.text}")
                return {"error": response.text, "status_code": response.status_code}

        except Exception as e:
            logger.error(f"Update error: {e}")
            return {"error": str(e)}

    def close_ticket(self, table: str, sys_id: str, close_notes: str) -> Dict:
        """Close a ticket with resolution notes."""
        close_fields = {
            "state": "3" if table == "change_request" else "6",  # Closed
            "close_code": "Successful" if table == "change_request" else "Solved (Permanently)",
            "close_notes": close_notes,
        }
        return self.update_ticket(table, sys_id, close_fields)

    def get_ticket(self, table: str, number: str) -> Dict:
        """Get a ticket by number (e.g., CHG0040001)."""
        session = self._get_session()
        if not session:
            return self._simulate_ticket(table, number)

        try:
            url = f"{self.config.table_api_url}/{table}?sysparm_query=number={number}&sysparm_limit=1"
            response = session.get(url, timeout=10)

            if response.status_code == 200:
                results = response.json().get("result", [])
                return results[0] if results else {}
            return {}

        except Exception as e:
            logger.error(f"Get ticket error: {e}")
            return {"error": str(e)}

    def get_open_changes(self) -> List[Dict]:
        """Get all open change requests."""
        session = self._get_session()
        if not session:
            return self._simulate_open_changes()

        try:
            url = (
                f"{self.config.table_api_url}/change_request"
                f"?sysparm_query=state!=-3^state!=3^ORDERBYDESCsys_created_on"
                f"&sysparm_limit=50"
                f"&sysparm_fields=number,short_description,state,priority,risk,"
                f"assignment_group,sys_created_on,start_date,end_date"
            )
            response = session.get(url, timeout=15)

            if response.status_code == 200:
                return response.json().get("result", [])
            return []

        except Exception as e:
            logger.error(f"Get open changes error: {e}")
            return self._simulate_open_changes()

    # ===================== INTERNAL HELPERS =====================

    def _create_record(self, table: str, payload: Dict) -> Dict:
        """Create a record in ServiceNow."""
        session = self._get_session()
        if not session:
            return self._simulate_response(table, payload)

        try:
            url = f"{self.config.table_api_url}/{table}"
            response = session.post(url, json=payload, timeout=15)

            if response.status_code in (200, 201):
                result = response.json().get("result", {})
                logger.info(f"Created {table}: {result.get('number', result.get('sys_id'))}")
                return result
            else:
                logger.error(f"Create failed: {response.status_code} - {response.text}")
                return {"error": response.text, "status_code": response.status_code}

        except Exception as e:
            logger.error(f"ServiceNow API error: {e}")
            return self._simulate_response(table, payload)

    def _create_or_update_record(self, table: str, payload: Dict, query: str) -> Dict:
        """Create or update a record based on a query."""
        session = self._get_session()
        if not session:
            return self._simulate_response(table, payload)

        try:
            # Check if record exists
            url = f"{self.config.table_api_url}/{table}?sysparm_query={query}&sysparm_limit=1"
            response = session.get(url, timeout=10)

            if response.status_code == 200:
                results = response.json().get("result", [])
                if results:
                    # Update existing
                    sys_id = results[0]["sys_id"]
                    return self.update_ticket(table, sys_id, payload)

            # Create new
            return self._create_record(table, payload)

        except Exception as e:
            return self._simulate_response(table, payload)

    # ===================== SIMULATION MODE =====================

    def _simulate_response(self, table: str, payload: Dict, sys_id: str = None) -> Dict:
        """Generate simulated response when ServiceNow is unavailable."""
        import random

        prefixes = {
            "change_request": "CHG",
            "incident": "INC",
            "sc_req_item": "RITM",
            "cmdb_ci_server": "CI",
        }
        prefix = prefixes.get(table, "REC")
        number = f"{prefix}{random.randint(100000, 999999):07d}"

        return {
            "sys_id": sys_id or f"sim-{datetime.now().strftime('%Y%m%d%H%M%S')}",
            "number": number,
            "short_description": payload.get("short_description", ""),
            "state": "New",
            "priority": payload.get("priority", "2"),
            "sys_created_on": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "assignment_group": payload.get("assignment_group", ""),
            "_simulated": True,
        }

    def _simulate_ticket(self, table: str, number: str) -> Dict:
        """Simulate a ticket lookup."""
        return {
            "number": number,
            "short_description": f"Simulated {number}",
            "state": "New",
            "priority": "2",
            "_simulated": True,
        }

    def _simulate_open_changes(self) -> List[Dict]:
        """Generate simulated open change requests."""
        return [
            {
                "number": "CHG0040001",
                "short_description": "[CRITICAL] CVE-2024-43498 - .NET Framework RCE",
                "state": "New",
                "priority": "1",
                "risk": "High",
                "assignment_group": "Windows Server Team",
                "sys_created_on": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            },
            {
                "number": "CHG0040002",
                "short_description": "[HIGH] CVE-2024-21338 - Windows Kernel EoP",
                "state": "Assess",
                "priority": "2",
                "risk": "Moderate",
                "assignment_group": "Windows Server Team",
                "sys_created_on": (datetime.now() - timedelta(hours=6)).strftime("%Y-%m-%d %H:%M:%S"),
            },
            {
                "number": "CHG0040003",
                "short_description": "[HIGH] CVE-2024-30078 - Wi-Fi Driver RCE",
                "state": "Authorize",
                "priority": "2",
                "risk": "Moderate",
                "assignment_group": "Windows Server Team",
                "sys_created_on": (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d %H:%M:%S"),
            },
        ]


# ==================== CONVENIENCE FACTORY ====================

def create_servicenow_client(
    instance_url: str = "https://dev218436.service-now.com",
    username: str = "admin",
    password: str = "",
) -> ServiceNowClient:
    """Factory function to create a configured ServiceNow client."""
    config = ServiceNowConfig(
        instance_url=instance_url,
        username=username,
        password=password,
    )
    return ServiceNowClient(config)
